<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rep_model"
 *
 * Auto generated by Extension Builder 2019-07-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'REP Model',
    'description'      => 'Handling Repair models',
    'category'         => 'plugin',
    'author'           => 'Frederic Haubold',
    'author_email'     => 'frederic-haubold@web.de',
    'state'            => 'stable',
    'uploadfolder'     => 0,
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '0.2.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '9.5.0 - 10.4.99',
        ],
        'conflicts' => [],
        'suggests'  => [],
    ],

];
